version: "3.7"
services:
  myS3client:
    container_name: mys3client
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
